import type { ReplayArtifact } from "./schema";
import type { ReplayVerifyResult } from "./verify";
import type { EvidenceProvenanceEntry } from "./project";

/**
 * Builds a concise Markdown incident report from a verified artifact.
 * Every number here is read directly from the artifact / derived tables the
 * UI already renders — nothing is fabricated for the export.
 */
export function buildMarkdownReport(
  artifact: ReplayArtifact,
  verify: ReplayVerifyResult,
  provenance: EvidenceProvenanceEntry[],
  compareAgainst?: ReplayArtifact,
): string {
  const lines: string[] = [];
  lines.push(`# Replay Lab report — ${artifact.identity.sessionId}`);
  lines.push("");
  lines.push(`- Scenario: \`${artifact.identity.scenarioId}\` (digest \`${artifact.identity.scenarioDigest.slice(0, 16)}\`)`);
  lines.push(`- Seed: ${artifact.identity.seed}`);
  lines.push(`- Final tick: ${artifact.finalTick} / ${artifact.identity.totalTicks}`);
  lines.push(`- Final score: ${artifact.scoreTotal.toFixed(2)}`);
  lines.push(`- Handled incidents: ${artifact.handledIncidents.join(", ") || "(none)"}`);
  lines.push(`- Still active at end: ${artifact.activeIncidents.join(", ") || "(none)"}`);
  lines.push(`- Truth events: ${artifact.eventCount} · Player events: ${artifact.playerEventCount}`);
  lines.push(`- Commands issued: ${artifact.commandTrace.length} · Assessments submitted: ${artifact.assessmentTrace.length}`);
  lines.push(`- Artifact hash: \`${artifact.artifactHash}\``);
  lines.push(`- Browser verification status: **${verify.status}** (never full PASS)`);
  lines.push(`- Integrity: **${verify.scopes.integrity}**`);
  lines.push(`- Semantic bindings: **${verify.scopes.semanticBindings}**`);
  lines.push(`- Truth replay: **${verify.scopes.truthReplay}**`);
  lines.push(`- Player projection replay: **${verify.scopes.playerReplay}**`);
  lines.push(`- stateDigest: **${verify.scopes.stateDigest}**`);
  lines.push(`- scenarioContentDigest: **${verify.scopes.scenarioContentDigest}**`);
  lines.push(`- engineProtocolCompatibility: **${verify.scopes.engineProtocolCompatibility}**`);
  lines.push(`- publicActionLedger: **${verify.scopes.publicActionLedger}**`);
  lines.push(`- authenticity: **${verify.scopes.authenticity}**`);
  if (verify.reasons.length > 0) {
    lines.push(`- Reasons: ${verify.reasons.join("; ")}`);
  }
  lines.push("");
  lines.push(
    "> Browser Replay Lab checks integrity and semantic bindings only. Authoritative full verification (compiled-scenario truth replay + player projection rebuild) requires the CLI: `null-city-run verify --artifact <path>`. A valid hash chain is tamper-evident only, not cryptographic authenticity.",
  );
  lines.push("");

  const distorted = provenance.filter((p) => p.distorted);
  lines.push("## Evidence provenance — false/late report influence");
  lines.push("");
  if (distorted.length === 0) {
    lines.push("No corrupted or delayed observations were recorded for this run.");
  } else {
    lines.push("| Evidence | Claim | Observed→Delivered | Delay | Distortion | Reported vs. truth |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const entry of distorted) {
      const distortionLabel = entry.isFalseReport
        ? "false report"
        : entry.corruptionType
          ? `corrupted (${entry.corruptionType})`
          : "delayed only";
      const contentDiff =
        entry.originalContent && entry.originalContent !== entry.reportedContent
          ? `"${entry.originalContent}" → "${entry.reportedContent}"`
          : `"${entry.reportedContent}"`;
      lines.push(
        `| \`${entry.evidenceId}\` | \`${entry.claimId}\` | T${entry.observedTick}→T${entry.deliveredTick} | ${entry.delayTicks}t | ${distortionLabel} | ${contentDiff} |`,
      );
    }
  }
  lines.push("");

  lines.push("## Command trace");
  lines.push("");
  lines.push("| Tick | Command | Outcome | Target | Detail |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const entry of artifact.commandTrace) {
    lines.push(
      `| T${entry.issuedTick} | ${entry.commandName} | ${entry.outcome} | ${entry.target ?? ""} | ${entry.errorMessage ?? ""} |`,
    );
  }
  lines.push("");

  if (compareAgainst) {
    lines.push("## Comparison");
    lines.push("");
    const sameScenario = compareAgainst.identity.scenarioDigest === artifact.identity.scenarioDigest;
    lines.push(`- Compared against: \`${compareAgainst.identity.sessionId}\``);
    lines.push(`- Same scenario digest: ${sameScenario ? "yes" : "no"}`);
    lines.push(`- Score delta (B − A): ${(compareAgainst.scoreTotal - artifact.scoreTotal).toFixed(2)}`);
    lines.push(`- Final tick delta (B − A): ${compareAgainst.finalTick - artifact.finalTick}`);
    lines.push(`- Commands A/B: ${artifact.commandTrace.length} / ${compareAgainst.commandTrace.length}`);
    lines.push("");
  }

  lines.push("---");
  lines.push(`_Generated by NullCity Replay Lab. Source artifact hash \`${artifact.artifactHash.slice(0, 16)}\`._`);
  return lines.join("\n");
}
