/**
 * M8 adversarial release-candidate suite.
 *
 * Runs every attack module against the real production surfaces and writes a
 * machine-readable + human-readable report under data/evidence/m8-adversarial/.
 *
 * Exit code:
 *   0  no open P0/P1 finding
 *   1  at least one open P0/P1 finding (release blocker)
 *   2  the suite itself failed to execute
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { Findings, REPO_ROOT, startHarness } from "./lib.mjs";

const MODULES = [
  ["A1 truth extraction", "./a1-truth-extraction.mjs"],
  ["A2 session scope and confused deputy", "./a2-session-scope.mjs"],
  ["A3 completed-run immutability", "./a3-immutability.mjs"],
  ["A4 snapshot, resume and event tampering", "./a4-snapshot-tamper.mjs"],
  ["A5 malformed and oversized payloads", "./a5-malformed-payloads.mjs"],
  ["A6 error isolation and bounded resources", "./a6-resource-isolation.mjs"],
  ["A7 adapter parity (SDK, MCP, benchmark)", "./a7-adapter-parity.mjs"],
];

const OUT_DIR = join(REPO_ROOT, "data", "evidence", "m8-adversarial");

function renderMarkdown(findings, environment) {
  const counts = findings.counts();
  const lines = [];
  lines.push("# M8 adversarial suite report");
  lines.push("");
  lines.push("Generated by `node scripts/adversarial/run-all.mjs` (`pnpm verify:adversarial`).");
  lines.push("");
  lines.push("## Environment");
  lines.push("");
  for (const [key, value] of Object.entries(environment)) {
    lines.push(`- \`${key}\`: ${value}`);
  }
  lines.push("");
  lines.push("## Totals");
  lines.push("");
  lines.push(`- attacks executed: ${counts.total}`);
  lines.push(`- defended: ${counts.defended}`);
  lines.push(`- vulnerable: ${counts.vulnerable} (P0 ${counts.P0}, P1 ${counts.P1}, P2 ${counts.P2}, P3 ${counts.P3})`);
  lines.push(`- reproduced and accepted as a documented limitation: ${counts.accepted}`);
  lines.push(`- blocked (not executable in this environment): ${counts.blocked}`);
  lines.push("");
  lines.push("## Results");
  lines.push("");
  lines.push("| ID | Category | Attack | Claim under test | Severity | Status | Observed |");
  lines.push("|---|---|---|---|---|---|---|");
  for (const item of findings.items) {
    const cell = (value) => String(value).replace(/\|/g, "\\|").replace(/\n/g, " ");
    lines.push(
      `| ${item.id} | ${item.category} | ${cell(item.title)} | ${cell(item.claim)} | ${item.severity} | ` +
        `${item.status} | ${cell(item.observed)} |`,
    );
  }
  lines.push("");
  if (findings.vulnerable.length > 0) {
    lines.push("## Open vulnerabilities");
    lines.push("");
    for (const item of findings.vulnerable) {
      lines.push(`- **${item.id} (${item.severity})** ${item.title} — ${item.observed}`);
    }
    lines.push("");
  }
  if (findings.acceptedItems.length > 0) {
    lines.push("## Accepted limitations (reproduced, not fixed)");
    lines.push("");
    for (const item of findings.acceptedItems) {
      lines.push(`- **${item.id} (${item.severity})** ${item.title}`);
      lines.push(`  - observed: ${item.observed}`);
      lines.push(`  - accepted because: ${item.rationale}`);
    }
    lines.push("");
  }
  if (findings.blockedItems.length > 0) {
    lines.push("## Blocked (unresolved risk, not a pass)");
    lines.push("");
    for (const item of findings.blockedItems) {
      lines.push(`- **${item.id} (${item.severity})** ${item.title} — ${item.observed}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

async function main() {
  const findings = new Findings();
  const environment = {
    node: process.version,
    platform: `${process.platform} ${process.arch}`,
    startedAt: "deterministic-report (wall clock intentionally omitted)",
  };

  // ADV_ONLY narrows the run while iterating on a single attack module. A
  // narrowed run never writes the report, so partial results cannot be
  // mistaken for release evidence.
  const only = process.env["ADV_ONLY"];
  const selected = only ? MODULES.filter(([, specifier]) => specifier.includes(only)) : MODULES;
  if (selected.length === 0) {
    throw new Error(`ADV_ONLY=${only} matched no attack module`);
  }

  for (const [label, specifier] of selected) {
    process.stdout.write(`\n== ${label} ==\n`);
    const module = await import(specifier);
    // Each module gets a fresh server so one attack cannot poison the next.
    const harness = await startHarness();
    try {
      await module.run(harness, findings);
    } finally {
      await harness.close();
    }
  }

  const counts = findings.counts();
  if (only) {
    process.stdout.write(`\nADV_ONLY run (${counts.total} attacks) — report not written\n`);
    process.exitCode = counts.P0 + counts.P1 > 0 ? 1 : 0;
    return;
  }
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(
    join(OUT_DIR, "report.json"),
    `${JSON.stringify({ environment, counts, findings: findings.items }, null, 2)}\n`,
    "utf8",
  );
  writeFileSync(join(OUT_DIR, "report.md"), `${renderMarkdown(findings, environment)}\n`, "utf8");

  process.stdout.write(
    `\nadversarial suite: ${counts.total} attacks, ${counts.defended} defended, ` +
      `${counts.vulnerable} vulnerable (P0 ${counts.P0} / P1 ${counts.P1} / P2 ${counts.P2} / P3 ${counts.P3}), ` +
      `${counts.accepted} accepted limitation(s), ${counts.blocked} blocked\n`,
  );
  process.stdout.write(`report: data/evidence/m8-adversarial/report.md\n`);

  if (counts.P0 > 0 || counts.P1 > 0) {
    process.stdout.write("\nRELEASE BLOCKER: open P0/P1 finding(s)\n");
    process.exitCode = 1;
    return;
  }
  process.stdout.write("no open P0/P1 findings\n");
}

main().catch((error) => {
  process.stderr.write(`adversarial suite failed to execute: ${error?.stack ?? String(error)}\n`);
  process.exitCode = 2;
});
